### PR TITLE
docs(flux): se actualiza documentación principal

### LINKED ISSUE #29: Mejora de la documentación
Se necesita mejorar la documentación principal de flux de manera detallada.

### PR DESCRIPTION
**Pull request by VictorJSV**
Se explica los pasos a instalar y se detalla el uso básico de la herramienta

close #29
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/carloshs92%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1372633%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/frontend-labs/flux/pull/30%23issuecomment-127417008%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-08-03T21%3A56%3A49Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1372633%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/carloshs92%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-08-03T21%3A57%3A01Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1372633%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/carloshs92%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A%20%5B%22https%3A//github.com/frontend-labs/flux/pull/30%23issuecomment-127417008%22%2C%20%22https%3A//github.com/frontend-labs/flux/pull/30%23issuecomment-127417041%22%5D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/carloshs92'></a>

<a href='https://www.codereviewhub.com/frontend-labs/flux/pull/30?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/frontend-labs/flux/pull/30?approve=0'></a>&nbsp;<a href='https://github.com/frontend-labs/flux/pull/30'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by andru255** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/frontend-labs/flux/pull/30'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by carloshs92** [comment]
:shipit:

**Comment by carloshs92** [comment]
:shipit:

**Comment by jansanchez** [comment]
:shipit:

**Comment by andru255** [comment]
:shipit:

**Comment by jansanchez** [comment]
@anareyna, Actualizando la documentación...

**Pull request merged**
