### PR TITLE
refact(config): Se estandariza la variable config

### PR DESCRIPTION
**Pull request by carloshs92**
- Todas las variables a exportar del archivo config.local.js sera enviado desde la variable CONFIG.
- Todo lo que este dentro de CONFIG será en minuscula por un tema de estética.
- El objeto tests almacenará todas las constantes relacionadas a las pruebas unitarias, funcionales, look and feel, entre otras.
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/jansanchez%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2623671%3Fv%3D3%22%7D%2C%20%22https%3A//github.com/andru255%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/729789%3Fv%3D3%22%7D%2C%20%22https%3A//github.com/VictorJSV%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5455561%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/frontend-labs/flux/pull/40%23issuecomment-128141271%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22A%20sido%20un%20gran%20pull%20request%2C%20gracias%20por%20su%20apoyo%20%40carloshs92%2C%20%40andru255%2C%20%40VictorJSV%5Cr%5Cn%5Cr%5CnAll%5Cu00ed%20les%20mando%20la%20ardisha.%5Cr%5Cn%5Cr%5Cn%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-08-05T20%3A38%3A35Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2623671%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/jansanchez%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-08-05T20%3A39%3A42Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5455561%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/VictorJSV%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-08-05T20%3A44%3A52Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/729789%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/andru255%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A%20%5B%22https%3A//github.com/frontend-labs/flux/pull/40%23issuecomment-128141271%22%2C%20%22https%3A//github.com/frontend-labs/flux/pull/40%23issuecomment-128141520%22%2C%20%22https%3A//github.com/frontend-labs/flux/pull/40%23issuecomment-128142545%22%5D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/jansanchez'></a><a href='https://github.com/andru255'></a><a href='https://github.com/VictorJSV'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/frontend-labs/flux/pull/40#issuecomment-128141271'>General Comment</a></b>
- <a href='https://github.com/jansanchez'></a> A sido un gran pull request, gracias por su apoyo @carloshs92, @andru255, @VictorJSV
Allí les mando la ardisha.
:shipit:

<a href='https://www.codereviewhub.com/frontend-labs/flux/pull/40?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/frontend-labs/flux/pull/40?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/frontend-labs/flux/pull/40?approve=0'></a>&nbsp;<a href='https://github.com/frontend-labs/flux/pull/40'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by andru255** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/frontend-labs/flux/pull/40'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by jansanchez** [comment]
:shipit:

**Comment by VictorJSV** [comment]
:shipit:

**Comment by andru255** [comment]
:shipit:

**Pull request merged**
