### PR TITLE
fix(jade-mixin):anchor of html elements

### PR DESCRIPTION
**Pull request by wilsson**
It's ready for code review.
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/pakgva%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5541960%3Fv%3D3%22%7D%2C%20%22https%3A//github.com/jansanchez%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2623671%3Fv%3D3%22%7D%2C%20%22https%3A//github.com/andru255%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/729789%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/frontend-labs/flux/pull/22%23issuecomment-71233377%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-01-23T17%3A50%3A02Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5541960%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/pakgva%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-01-23T17%3A59%3A01Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/729789%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/andru255%22%7D%7D%2C%20%7B%22body%22%3A%20%22Esta%20bueno%20el%20cambio%2C%20lo%20que%20debemos%20ver%20es%20un%20standard%20para%20los%20nombres%20de%20variables%20dentro%20de%20los%20mixins%2C%20cuando%20estos%20sean%20palabras%20reservadas.%22%2C%20%22created_at%22%3A%20%222015-01-23T18%3A04%3A50Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2623671%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/jansanchez%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-01-23T18%3A06%3A14Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2623671%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/jansanchez%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A%20%5B%22https%3A//github.com/frontend-labs/flux/pull/22%23issuecomment-71233377%22%2C%20%22https%3A//github.com/frontend-labs/flux/pull/22%23issuecomment-71234872%22%2C%20%22https%3A//github.com/frontend-labs/flux/pull/22%23issuecomment-71235800%22%2C%20%22https%3A//github.com/frontend-labs/flux/pull/22%23issuecomment-71236037%22%5D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/pakgva'></a><a href='https://github.com/jansanchez'></a><a href='https://github.com/andru255'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/frontend-labs/flux/pull/22#issuecomment-71233377'>General Comment</a></b>
- <a href='https://github.com/pakgva'></a> :shipit:
- <a href='https://github.com/andru255'></a> :shipit:
- <a href='https://github.com/jansanchez'></a> Esta bueno el cambio, lo que debemos ver es un standard para los nombres de variables dentro de los mixins, cuando estos sean palabras reservadas.

<a href='https://www.codereviewhub.com/frontend-labs/flux/pull/22?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/frontend-labs/flux/pull/22?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/frontend-labs/flux/pull/22?approve=0'></a>&nbsp;<a href='https://github.com/frontend-labs/flux/pull/22'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by andru255** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/frontend-labs/flux/pull/22'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by pakgva** [comment]
:shipit:

**Comment by andru255** [comment]
:shipit:

**Comment by jansanchez** [comment]
Esta bueno el cambio, lo que debemos ver es un standard para los nombres de variables dentro de los mixins, cuando estos sean palabras reservadas.

**Comment by jansanchez** [comment]
:shipit:

**Pull request merged**
