### PR TITLE
refactor(flux): Estandarización de archivos

### PR DESCRIPTION
**Pull request by pakgva**
@jansanchez , @wilsson, @andru255 y @jjhoncv  CR por favor
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/pakgva%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5541960%3Fv%3D3%22%7D%2C%20%22https%3A//github.com/jansanchez%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2623671%3Fv%3D3%22%7D%2C%20%22https%3A//github.com/wilsson%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/4754339%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/frontend-labs/flux/pull/19%23issuecomment-71093042%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-01-22T20%3A31%3A52Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2623671%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/jansanchez%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-01-22T21%3A06%3A27Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5541960%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/pakgva%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-01-22T21%3A06%3A53Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/4754339%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/wilsson%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-01-22T21%3A08%3A51Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2623671%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/jansanchez%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-01-22T21%3A09%3A14Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2623671%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/jansanchez%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A%20%5B%22https%3A//github.com/frontend-labs/flux/pull/19%23issuecomment-71093042%22%2C%20%22https%3A//github.com/frontend-labs/flux/pull/19%23issuecomment-71098625%22%2C%20%22https%3A//github.com/frontend-labs/flux/pull/19%23issuecomment-71098703%22%2C%20%22https%3A//github.com/frontend-labs/flux/pull/19%23issuecomment-71099054%22%2C%20%22https%3A//github.com/frontend-labs/flux/pull/19%23issuecomment-71099115%22%5D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/pakgva'></a><a href='https://github.com/jansanchez'></a><a href='https://github.com/wilsson'></a>

<a href='https://www.codereviewhub.com/frontend-labs/flux/pull/19?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/frontend-labs/flux/pull/19?approve=0'></a>&nbsp;<a href='https://github.com/frontend-labs/flux/pull/19'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by andru255** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/frontend-labs/flux/pull/19'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by jansanchez** [comment]
:shipit:

**Comment by pakgva** [comment]
:shipit:

**Comment by wilsson** [comment]
:shipit:

**Comment by jansanchez** [comment]
:shipit:

**Comment by jansanchez** [comment]
:shipit:

**Pull request merged**
