### PR TITLE
Development

### PR DESCRIPTION
**Pull request by jansanchez**
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/juanpablocs21%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/9310466%3Fv%3D3%22%7D%2C%20%22https%3A//github.com/jansanchez%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2623671%3Fv%3D3%22%7D%2C%20%22https%3A//github.com/andru255%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/729789%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/frontend-labs/flux/pull/24%23issuecomment-106938654%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-05-29T21%3A20%3A05Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2623671%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/jansanchez%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-05-29T21%3A36%3A32Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/9310466%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/juanpablocs21%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-05-29T21%3A37%3A48Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/729789%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/andru255%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A%20%5B%22https%3A//github.com/frontend-labs/flux/pull/24%23issuecomment-106938654%22%2C%20%22https%3A//github.com/frontend-labs/flux/pull/24%23issuecomment-106941615%22%2C%20%22https%3A//github.com/frontend-labs/flux/pull/24%23issuecomment-106941767%22%5D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/juanpablocs21'></a><a href='https://github.com/jansanchez'></a><a href='https://github.com/andru255'></a>

<a href='https://www.codereviewhub.com/frontend-labs/flux/pull/24?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/frontend-labs/flux/pull/24?approve=0'></a>&nbsp;<a href='https://github.com/frontend-labs/flux/pull/24'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by andru255** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/frontend-labs/flux/pull/24'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by jansanchez** [comment]
:shipit:

**Comment by juanpablocs21** [comment]
:shipit:

**Comment by andru255** [comment]
:shipit:

**Pull request merged**
