### PR TITLE
feat(modules): Configuración de undescore template y reseteo de cookies

### PR DESCRIPTION
**Pull request by pakgva**
Se agregaron 2 nuevos módulos para configurar la utilidad template de underscore y el reseteo de cookies.

@andru255, @jansanchez, @mfyance, @jjhoncv y @wilsson. CR por favor.
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/andru255%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/729789%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/frontend-labs/flux/pull/16%23issuecomment-71034233%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-01-22T15%3A09%3A41Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/729789%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/andru255%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%3Agun%3A%22%2C%20%22created_at%22%3A%20%222015-01-22T15%3A18%3A34Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5541960%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/pakgva%22%7D%7D%2C%20%7B%22body%22%3A%20%22Se%20rechaza%20el%20pull%20request%20ya%20que%20se%20debe%20realizar%20el%20merge%20con%20la%20rama%20staging.%22%2C%20%22created_at%22%3A%20%222015-01-22T15%3A36%3A44Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2623671%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/jansanchez%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A%20%5B%22https%3A//github.com/frontend-labs/flux/pull/16%23issuecomment-71034233%22%2C%20%22https%3A//github.com/frontend-labs/flux/pull/16%23issuecomment-71035771%22%2C%20%22https%3A//github.com/frontend-labs/flux/pull/16%23issuecomment-71039098%22%5D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/andru255'></a>

- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/frontend-labs/flux/pull/16#issuecomment-71034233'>General Comment</a></b>
- <a href='https://github.com/andru255'></a> :shipit:
- <a href='https://github.com/pakgva'></a> :shipit::gun:
- <a href='https://github.com/jansanchez'></a> Se rechaza el pull request ya que se debe realizar el merge con la rama staging.

<a href='https://www.codereviewhub.com/frontend-labs/flux/pull/16?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/frontend-labs/flux/pull/16?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/frontend-labs/flux/pull/16?approve=0'></a>&nbsp;<a href='https://github.com/frontend-labs/flux/pull/16'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by andru255** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/frontend-labs/flux/pull/16'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by andru255** [comment]
:shipit:

**Comment by pakgva** [comment]
:shipit::gun:

**Comment by jansanchez** [comment]
Se rechaza el pull request ya que se debe realizar el merge con la rama staging.

**Pull request closed without merging**
