### PR TITLE
refactor(jadeflux): Estandarización de archivos

### PR DESCRIPTION
**Pull request by pakgva**
- Se incluye un refactor para un modulo de coffee según convención

@andru255, @wilsson y @jjhoncv CR por favor.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/frontend-labs/flux/pull/18%23issuecomment-71066780%22%2C%20%22https%3A//github.com/frontend-labs/flux/pull/18%23issuecomment-71066797%22%2C%20%22https%3A//github.com/frontend-labs/flux/pull/18%23issuecomment-71080939%22%2C%20%22https%3A//github.com/frontend-labs/flux/pull/18%23issuecomment-71081101%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/frontend-labs/flux/pull/18%23issuecomment-71066780%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Buen%20refactor%21%22%2C%20%22created_at%22%3A%20%222015-01-22T18%3A01%3A34Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2623671%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/jansanchez%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-01-22T18%3A01%3A40Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2623671%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/jansanchez%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-01-22T19%3A21%3A11Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/729789%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/andru255%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-01-22T19%3A22%3A03Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/4754339%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/wilsson%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/jansanchez%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2623671%3Fv%3D3%22%7D%2C%20%22https%3A//github.com/andru255%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/729789%3Fv%3D3%22%7D%2C%20%22https%3A//github.com/wilsson%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/4754339%3Fv%3D3%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/jansanchez'></a><a href='https://github.com/andru255'></a><a href='https://github.com/wilsson'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/frontend-labs/flux/pull/18#issuecomment-71066780'>General Comment</a></b>
- <a href='https://github.com/jansanchez'></a> Buen refactor!

<a href='https://www.codereviewhub.com/frontend-labs/flux/pull/18?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/frontend-labs/flux/pull/18?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/frontend-labs/flux/pull/18?approve=0'></a>&nbsp;<a href='https://github.com/frontend-labs/flux/pull/18'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by andru255** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/frontend-labs/flux/pull/18'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by jansanchez** [comment]
Buen refactor!

**Comment by jansanchez** [comment]
:shipit:

**Comment by andru255** [comment]
:shipit:

**Comment by wilsson** [comment]
:shipit:

**Pull request merged**
