### PR TITLE
Add semicolons, fix word and add mixin form

### PR DESCRIPTION
**Pull request by renaco**
Agrego puntos y comas, arreglo palabra en comentario y agrego mixin para formularios
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/frontend-labs/flux/pull/59%23issuecomment-229163100%22%2C%20%22https%3A//github.com/frontend-labs/flux/pull/59%23issuecomment-229165307%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/frontend-labs/flux/pull/59%23issuecomment-229163100%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Se%20cerrar%5Cu00e1%20el%20pull%20request%20debido%20a%20que%20contiene%20commits%20%5C%22WiP%5C%22.%22%2C%20%22created_at%22%3A%20%222016-06-28T19%3A54%3A16Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5455561%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/VictorJSV%22%7D%7D%2C%20%7B%22body%22%3A%20%22FYI%20%40renaco%20%22%2C%20%22created_at%22%3A%20%222016-06-28T20%3A02%3A10Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2623671%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/jansanchez%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/frontend-labs/flux/pull/59#issuecomment-229163100'>General Comment</a></b>
- <a href='https://github.com/VictorJSV'></a> Se cerrará el pull request debido a que contiene commits "WiP".
- <a href='https://github.com/jansanchez'></a> FYI @renaco

<a href='https://www.codereviewhub.com/frontend-labs/flux/pull/59?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/frontend-labs/flux/pull/59?approve=1'></a>&nbsp;<a href='https://github.com/frontend-labs/flux/pull/59'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by andru255** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/frontend-labs/flux/pull/59'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by VictorJSV** [comment]
Se cerrará el pull request debido a que contiene commits "WiP".

**Comment by jansanchez** [comment]
FYI @renaco

**Comment by tina-3** [comment]
#59

**Pull request closed without merging**
