### PR TITLE
Adding first english version for documentation

### LINKED ISSUE #35: docs(readme): traducir documentación principal a inglés
@anareyna, Favor tu apoyo para traducir el contenido del README.md al idioma Inglés.

> El contenido en español esta guardado en el archivo README-es.md.

### PR DESCRIPTION
**Pull request by jansanchez**
Adding first english version for documentation. This closes #35 by @anareyna 

CR please.
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/jansanchez%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2623671%3Fv%3D3%22%7D%2C%20%22https%3A//github.com/VictorJSV%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5455561%3Fv%3D3%22%7D%2C%20%22https%3A//github.com/carloshs92%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1372633%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/frontend-labs/flux/pull/37%23issuecomment-127685522%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-08-04T17%3A29%3A13Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2623671%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/jansanchez%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-08-04T17%3A32%3A57Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5455561%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/VictorJSV%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Azap%3A%22%2C%20%22created_at%22%3A%20%222015-08-04T17%3A34%3A03Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/4754339%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/wilsson%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-08-04T17%3A42%3A12Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1372633%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/carloshs92%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%2C%20%22Commit%2077b3e0464bbc903a2d8ef6e8ef6d56f70f0acd09%20README.md%2035%2018%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/frontend-labs/flux/commit/77b3e0464bbc903a2d8ef6e8ef6d56f70f0acd09%23commitcomment-12522608%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22ditto%22%2C%20%22created_at%22%3A%20%222015-08-04T17%3A35%3A46Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5541960%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/pakgva%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%3Ca%20href%3D%27%23crh-update-none%27%3E%3C/a%3E%22%2C%20%22created_at%22%3A%20%222015-08-04T21%3A22%3A15Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2623671%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/jansanchez%22%7D%7D%5D%2C%20%22title%22%3A%20%22File%3A%20README.md%3AL18%20%2877b3e04%29%22%7D%2C%20%22Commit%2077b3e0464bbc903a2d8ef6e8ef6d56f70f0acd09%20README.md%2028%2011%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/frontend-labs/flux/commit/77b3e0464bbc903a2d8ef6e8ef6d56f70f0acd09%23commitcomment-12522606%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40anareyna%20fix%20identation%22%2C%20%22created_at%22%3A%20%222015-08-04T17%3A35%3A36Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5541960%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/pakgva%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%3Ca%20href%3D%27%23crh-update-none%27%3E%3C/a%3E%22%2C%20%22created_at%22%3A%20%222015-08-04T21%3A22%3A15Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2623671%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/jansanchez%22%7D%7D%5D%2C%20%22title%22%3A%20%22File%3A%20README.md%3AL11%20%2877b3e04%29%22%7D%2C%20%22Commit%206dedd0cdc9b0a1110f2e240128d6745bb05af62a%20frontend/package.json%205%2014%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/frontend-labs/flux/commit/6dedd0cdc9b0a1110f2e240128d6745bb05af62a%23commitcomment-12522934%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40carloshs92%20corregir%20aqui%20la%20indentaci%5Cu00f3n.%22%2C%20%22created_at%22%3A%20%222015-08-04T17%3A50%3A44Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2623671%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/jansanchez%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%3Ca%20href%3D%27%23crh-update-complete%27%3E%3C/a%3E%22%2C%20%22created_at%22%3A%20%222015-08-04T21%3A22%3A16Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2623671%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/jansanchez%22%7D%7D%5D%2C%20%22title%22%3A%20%22File%3A%20frontend/package.json%3AL14%20%286dedd0c%29%22%7D%7D%2C%20%22processed%22%3A%20%5B%22https%3A//github.com/frontend-labs/flux/pull/37%23issuecomment-127685522%22%2C%20%22https%3A//github.com/frontend-labs/flux/pull/37%23issuecomment-127686398%22%2C%20%22https%3A//github.com/frontend-labs/flux/pull/37%23issuecomment-127686597%22%2C%20%22https%3A//github.com/frontend-labs/flux/pull/37%23issuecomment-127688683%22%2C%20%22https%3A//github.com/frontend-labs/flux/commit/77b3e0464bbc903a2d8ef6e8ef6d56f70f0acd09%23commitcomment-12522606%22%2C%20%22https%3A//github.com/frontend-labs/flux/commit/77b3e0464bbc903a2d8ef6e8ef6d56f70f0acd09%23commitcomment-12522608%22%2C%20%22https%3A//github.com/frontend-labs/flux/commit/77b3e0464bbc903a2d8ef6e8ef6d56f70f0acd09%23commitcomment-12527279%22%2C%20%22https%3A//github.com/frontend-labs/flux/commit/77b3e0464bbc903a2d8ef6e8ef6d56f70f0acd09%23commitcomment-12527280%22%2C%20%22https%3A//github.com/frontend-labs/flux/commit/6dedd0cdc9b0a1110f2e240128d6745bb05af62a%23commitcomment-12522934%22%2C%20%22https%3A//github.com/frontend-labs/flux/commit/6dedd0cdc9b0a1110f2e240128d6745bb05af62a%23commitcomment-12527282%22%5D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/jansanchez'></a><a href='https://github.com/VictorJSV'></a><a href='https://github.com/carloshs92'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/frontend-labs/flux/pull/37#issuecomment-127685522'>General Comment</a></b>
- <a href='https://github.com/jansanchez'></a> :shipit:
- <a href='https://github.com/VictorJSV'></a> :shipit:
- <a href='https://github.com/wilsson'></a> :zap:
- [x] <a href='#crh-comment-Commit 77b3e0464bbc903a2d8ef6e8ef6d56f70f0acd09 README.md 28 11'></a> &nbsp;<b><a href='https://github.com/frontend-labs/flux/commit/77b3e0464bbc903a2d8ef6e8ef6d56f70f0acd09#commitcomment-12522606'>File: README.md:L11 (77b3e04)</a></b>
- <a href='https://github.com/pakgva'></a> @anareyna fix identation
- [x] <a href='#crh-comment-Commit 77b3e0464bbc903a2d8ef6e8ef6d56f70f0acd09 README.md 35 18'></a> &nbsp;<b><a href='https://github.com/frontend-labs/flux/commit/77b3e0464bbc903a2d8ef6e8ef6d56f70f0acd09#commitcomment-12522608'>File: README.md:L18 (77b3e04)</a></b>
- <a href='https://github.com/pakgva'></a> ditto
- [x] <a href='#crh-comment-Commit 6dedd0cdc9b0a1110f2e240128d6745bb05af62a frontend/package.json 5 14'></a> &nbsp;<b><a href='https://github.com/frontend-labs/flux/commit/6dedd0cdc9b0a1110f2e240128d6745bb05af62a#commitcomment-12522934'>File: frontend/package.json:L14 (6dedd0c)</a></b>
- <a href='https://github.com/jansanchez'></a> @carloshs92 corregir aqui la indentación.

<a href='https://www.codereviewhub.com/frontend-labs/flux/pull/37?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/frontend-labs/flux/pull/37?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/frontend-labs/flux/pull/37?approve=0'></a>&nbsp;<a href='https://github.com/frontend-labs/flux/pull/37'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by andru255** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/frontend-labs/flux/pull/37'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by jansanchez** [comment]
:shipit:

**Comment by VictorJSV** [comment]
:shipit:

**Comment by wilsson** [comment]
:shipit:

**Comment by carloshs92** [comment]
:shipit:

**Comment by jansanchez** [comment]
Ya tenemos documentación en Inglés!!!

Gracias Muchachios!!


@anareyna, @andru255, @VictorJSV, @carloshs92, @wilsson, @pakgva y todos los demás!

**Comment by jansanchez** [comment]
:+1:

**Pull request merged**
